### PR TITLE
Adding affected MEW users

### PR DESCRIPTION
**Pull request by kvhnuke**

### CODE REVIEW

**Comment by 0age** [comment]
Looks like 44 of the supplied addresses (one of which appears to be a transaction hash) are not in the [superset](https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql) — any idea what could be causing these to fail?

**Comment by 0age** [comment]
[This tx](https://etherscan.io/tx/0x454149b00b232e754e08bfcaa7a0e49158f6469aed17912c9566e23f8125112a) looks like one of the trades that failed — the superset includes failed calls, but only if they make it to the uniswap portion of the call.

**Comment by kvhnuke** [comment]
got it, will remove them and resubmit

**Comment by kvhnuke** [comment]
> Looks like 44 of the supplied addresses (one of which appears to be a transaction hash) are not in the [superset](https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql) — any idea what could be causing these to fail?

not sure where the (two addresses, that looked like tx hash) came from

**Pull request merged**
