### PR TITLE
Projects/opyn

### PR DESCRIPTION
**Pull request by ugolino**
- Added addresses that interacted with Uniswap through Opyn that not received the Airdrop
- Added the script to gather the list of addresses in the folder /scripts 
- Added the README with instructions on how to run the script

### CODE REVIEW

**Comment by 0age** [comment]
Hey @ugolino — it looks like there are a few accounts that are missing from the [bigquery set](https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql). I've made a modification to the query to include all `to` accounts that are included as part of the callstack for any transaction that touches Uniswap... if that doesn't solve the issue, do you have any idea as to what might be causing the mismatch?

**Comment by 0age** [comment]
Updated the superset of accounts and there are still 54 accounts in your submitted list that don't match. I'm also unable to locate where Uniswap is being touched when I poke around on a few of them. You'll need to either:
- assist in diagnosing where Uniswap is being called in these accounts, and why they might be missing from the superset
- filter out those accounts (could make another PR for just those accounts as well so we can get the majority included for now!)

**Comment by ugolino** [comment]
hey @0age thanks for looking into this. Happy to assist you on this. Do you have the list of the 54 accounts you mentioned so I can look into them?
Last question, is there a deadline to close this?

**Comment by nadavhollander** [comment]
@ugolino You can find the list of addresses in the failing tests:
```
[
    +   "0x033a5436ba4e183e63349f83a06127bf7e1e1a91",
    +   "0x0c8e77b6ecbf83ec67bb4e00c9e86fa50e703381",
    +   "0x0e4c8e7494beddef1fc52c43f480b703638a7639",
    +   "0x112efae30e371e43ff9719965048bff70f519e1c",
    +   "0x15e397d1a7a08174bd1fc6cd4f28188b073dab08",
    +   "0x2228b2f60a16eb8a6b28e27481fdde540515283e",
    +   "0x2a0871d2450eb0fa06a94f169ea09215ca6c5ae2",
    +   "0x2b5b3c98ad9b7c6b814edc5e63dd487e6bc5f454",
    +   "0x2db6320c647fe6af6ef096523387e43efc7ebe35",
    +   "0x2f160846a9d30779e5991ef776389327e26ade6a",
    +   "0x30c37afd327b23f1a72466fb60e0197962274f30",
    +   "0x32a948ba39fc70382c3a7db671f274ec59a56523",
    +   "0x348cef87ebf814c148301082d22eb783bab2ac15",
    +   "0x37badf1172eeb0f8269f9d5e8472651b1b6660c6",
    +   "0x41700c3638eda32a9af5088250b321bafcf0e8f1",
    +   "0x45c3e85c6586501883141f7e33165cd5d19a9c9a",
    +   "0x45fc0f37fed5a45ee35287abb8ab95f33c7a51ed",
    +   "0x46c3a490206b1d33d0e9334e7395dbd3e6aa8d33",
    +   "0x494ac8a1e91fd7a9f9aa99e9c0076ee9304551c7",
    +   "0x4990a1ba078ac31eb955b1285516bc4e391f0e5e",
    +   "0x4bc3a95dcc417aa9856fb50c93d0f73aa477dfb6",
    +   "0x4dd7d405e83b9167d30831c0e2aa2faf6b874342",
    +   "0x52a94df5ee455a5f757c5a6d7795a17f4e1255a8",
    +   "0x58f56615180a8eea4c462235d9e215f72484b4a3",
    +   "0x5caff38d10145e97a050731dc4e7dcb55ddbae1d",
    +   "0x5cc3a4c846ab8b0b78a729b8b1a50e2e0bb66740",
    +   "0x6438822d8f3cfb6c440c48f1d6809eb53d854c9c",
    +   "0x6b00e0465b7f2c45a0160d9ba1e301182caf2c26",
    +   "0x78ea89a00814f76cf511971e8ab616ffc9edf264",
    +   "0x79ee22a5a4ed44a141a8f81209a7da9d1e96103b",
    +   "0x7a00db0bdfd1ab9debbf63f4e93b14bbd0f6570c",
    +   "0x846e2c5d79aa294e6b0c01ccea6b04481bbedea3",
    +   "0x88e79af0c051a0cd0dda7138f647e0377c907e61",
    +   "0x8a368801a9a08a6e979978c6b831befa7b30f0ad",
    +   "0x8dfd1f84cf9d29b4aaf6b2baf1c509164f73473e",
    +   "0x9265094b972d83b4b27360672076873549a6e2a4",
    +   "0x9e13d58e67ea41010009b80b8548286aecb456b6",
    +   "0xa093d30c3fceaa86ee0a80b0abf77c3ee13d9181",
    +   "0xb4695458f61a4dfb02c7f73b96d9253634881d4b",
    +   "0xb72e60ea1d0c04605f406c158dce9ac6ae6d224c",
    +   "0xbee4eaef515072c41b23cbe937d48d8207de2e32",
    +   "0xc972ff87064d46116e19dbe67252e0188c7d5ac0",
    +   "0xcc7f98e65c6e2689b75bf2d817515da3006e967d",
    +   "0xce6bb0d052a567c42d9665fe730241f91bc1233f",
    +   "0xd0a0aa65614f7c1d43720b04f94102718a26b7ff",
    +   "0xd106f43b308bdf145bf7ec7ce1b7f2dcc05474a4",
    +   "0xd56612c7e7a0ef25eab46807c86466e61800e3a6",
    +   "0xdff54c3fcf5931f33365989d42f94aade88d0bed",
    +   "0xe520b52bb7ab95612b135e0977d026ce722ad339",
    +   "0xef5793b068f04d9b8f839d3d2045b101a0da676f",
    +   "0xf2178be96206631677fdfca1173be5712f628a31",
    +   "0xf4e9eb84137359e360a3305f802af4280475e995",
    +   "0xfd1ddbffdb2ce3e9a277598e39835df3e9f21793",
    + ]
```

**Comment by antoncoding** [comment]
@nadavhollander I've opened another PR #13 to exclude these addresses. You can close this one now.

**Pull request closed without merging**
