### PR TITLE
Add affected 0x API users

### PR DESCRIPTION
**Pull request by alexkroeger**
Added users of 0x API that traded on Uniswap v1 or v2 indirectly *and* were not part of the original airdrop.

### CODE REVIEW

**Comment by alexkroeger** [comment]
@nadavhollander  @graemecode the PR is failing tests, but I think the list that is being checked against is not comprehensive.

An example user that failed the test is `0x094b1aa08a107340baa421ba6013dbda722d71ed`. However, we can see in this [transaction](https://etherscan.io/tx/0xeb3e5a8cd957d0294e115129daf43645a05dff7e579366947316a8a769fe2f3a) the user is receiving LINK from Uniswap. The issue might be the list of addresses doesn't account for meta-transactions submitted on behalf of the user.

**Comment by graemecode** [comment]
> @nadavhollander @graemecode the PR is failing tests, but I think the list that is being checked against is not comprehensive.
> 
> An example user that failed the test is `0x094b1aa08a107340baa421ba6013dbda722d71ed`. However, we can see in this [transaction](https://etherscan.io/tx/0xeb3e5a8cd957d0294e115129daf43645a05dff7e579366947316a8a769fe2f3a) the user is receiving LINK from Uniswap. The issue might be the list of addresses doesn't account for meta-transactions submitted on behalf of the user.

Interesting. Yes, we might have to update the query. We're specifically using `from_address` in any traces for transactions submitted to the Uniswap Tokens, and do not include those addresses that are the recipient of the token. Will consider and update tomorrow.

**Comment by 0age** [comment]
Hey @alexkroeger,

We [updated the bigquery SQL command](https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql) used to generate the superset of accounts to include all addresses that received a token transfer as part of a transaction that touched uniswap — it includes the example user you supplied, but there are still failing addresses in the list you've supplied. One thing that just occurred to me is that this likely won't catch _ether_ transfers — it would be helpful if you could assist in triaging on this front!

**Comment by alexkroeger** [comment]
> Hey @alexkroeger,
> 
> We [updated the bigquery SQL command](https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql) used to generate the superset of accounts to include all addresses that received a token transfer as part of a transaction that touched uniswap — it includes the example user you supplied, but there are still failing addresses in the list you've supplied. One thing that just occurred to me is that this likely won't catch _ether_ transfers — it would be helpful if you could assist in triaging on this front!

@0age I reran the locally and it looks like there is now only 1 offending address--a contract that made a 'fill' with 0 amounts.  I can exclude that and I think it should be good to go. I think this PR needs to be rebased in order to test against the most recent file.

**Comment by alexkroeger** [comment]
@0age tests passing 👍

**Pull request merged**
