### PR TITLE
adding Paraswap/Uniswap traders

### PR DESCRIPTION
**Pull request by mounibec**

### CODE REVIEW

**Comment by nadavhollander** [comment]
@mounibec tests are failing as it seems a large portion of the addresses you've submitted don't fall within the superset of accounts we deem to be validly excluded.

The superset of accounts includes:

- every `from` and `to` address that is part of any transaction where a uniswap contract is called at some point
- every `to` address for any token transfer that is part of any transaction where a uniswap contract is called at some point

And excludes...

- every address included in the initial UNI allocation

Is there any reason you'd be aware of for why these addresses aren't fitting within the superset we pulled?

**Comment by mounibec** [comment]
> @mounibec tests are failing as it seems a large portion of the addresses you've submitted don't fall within the superset of accounts we deem to be validly excluded.
> 
> The superset of accounts includes:
> 
> * every `from` and `to` address that is part of any transaction where a uniswap contract is called at some point
> * every `to` address for any token transfer that is part of any transaction where a uniswap contract is called at some point
> 
> And excludes...
> 
> * every address included in the initial UNI allocation
> 
> Is there any reason you'd be aware of for why these addresses aren't fitting within the superset we pulled?

Fixed!

**Comment by nadavhollander** [comment]
LGTM, merging.

**Comment by abonn** [comment]
Hmm. I have a TX hash of my Monolith wallet interacting with Paraswap and the Uni router but my address is not listed in this list. You can see the TX here: https://etherscan.io/tx/0xff637137a04c30bdacabf59f4fa77c17586de08c3db564cb618ee8cb9b6dc4dd

**Comment by abonn** [comment]
Here is a tx from a Monolith user which fits the criteria but is not included in the list: https://etherscan.io/tx/0xff637137a04c30bdacabf59f4fa77c17586de08c3db564cb618ee8cb9b6dc4dd 

Hmm...

**Comment by mounibec** [comment]
@nadavhollander Many Monolith users are in the superset but they have no claim on $UNI.

**Comment by abonn** [comment]
@mounibec is it because the Monolith user addresses are contract addresses?

**Comment by ryanc414** [comment]
I haven't checked for all of our users but we think it's possible that the EOA address ("gas tank" to our customers) was included in this list instead of the smart contract address typically used to receive tokens. If this is the case, we could provide instructions to our users for how the can claim UNI for their EOA address + then send it to their smart-contract wallet.

**Comment by abonn** [comment]
@ryanc414 In my case, the list includes both my EOA address and contract address.

**Comment by camchis** [comment]
Seems like Paraswap have missed some Monolith users, my EOA and Smart Contract Wallet address are not included and I had a trade go through Uniswap. The valid list includes both my EOA and Smart Contract Wallet address but neither are in Paraswap's list, same as @abonn.

**Comment by ryanc414** [comment]
So I checked our known swap users prior to the 1st September cutoff date and filtered those which interacted with the uniswap V2 contract (https://etherscan.io/address/0x7a250d5630b4cf539739df2c5dacb4c659f2488d) via Paraswap. Here is a list of wallet addresses with an example transaction hash that interacts with Uni V2: https://github.com/ryanc414/excluded-uni-airdrop-users/blob/monolith/projects/ParaSwap/monolith_uni_v2.csv

I haven't yet cross-referenced with the paraswap list or against the EOA addresses associated with each wallet. Also, I'm not sure which other uniswap contract addresses are considered "in-scope" for this proposal.

**Comment by mounibec** [comment]
To recap the issue with Monolith users:

The gas talk addresses (used for paying the gas) that were considered on the superset and not the contract wallets that are used in the app. We'll provide the whole mapping for those

**Comment by ryanc414** [comment]
So it's a small inconvenience for our users if they had to claim using the gas tank address, but ultimately we can walk them through how to do that. However, from looking at our data + onchain data, I've managed to find 19 user accounts who traded through uniswap V2 via paraswap at least once but neither their contract wallet or EOA address are included on the list attached to this PR: https://github.com/ryanc414/excluded-uni-airdrop-users/blob/monolith/projects/ParaSwap/paraswap_excluded.csv

Would it be possible for these excluded addresses to be included before the proposal is finalised? Thanks!

**Pull request merged**
