### PR TITLE
projects/eidoo

### PR DESCRIPTION
**Pull request by mpolci**

### CODE REVIEW

**Comment by 0age** [comment]
Hey @mpolci — looks like there are six accounts (one appears to be two accounts concatenated) that are not in the [https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql](superset). Can you a) remove those or b) help diagnose why they aren't in the superset?

**Comment by mpolci** [comment]
> Hey @mpolci — looks like there are six accounts (one appears to be two accounts concatenated) that are not in the [superset](https://github.com/dharma-eng/retroactive-query/blob/master/src/12_candidate_proxy_airdrop_accounts.sql). Can you a) remove those or b) help diagnose why they aren't in the superset?

Could you give me the six addresses so I can check?

**Comment by 0age** [comment]
```    +   "0x04661d1e0a5c6d8436ca58de116d524a66eeeede",
    +   "0x3e16370fc214f139903aaaf43cd2e46740c89c9c",
    +   "0x940cc0ae46ba774be0f11669b9e78a3f1b10b6b8",
    +   "0x9696d09611a52cec3d2b3019e1c7b2178115a4910x4a538eb5d5e507aee284ffe918f67f81b6559836",
    +   "0xa2db46945825c50af082bc026bc4750723adfc83",
    +   "0xfb0fce9d94f3f69d419dbf11cf35bed84a501034",```

**Comment by mpolci** [comment]
> 0x9696d09611a52cec3d2b3019e1c7b2178115a4910x4a538eb5d5e507aee284ffe918f67f81b6559836

this line is not in our accounts.txt, neither the firt part 0x9696d09611a52cec3d2b3019e1c7b2178115a491 is in our file,  but only the second part 0x4a538eb5d5e507aee284ffe918f67f81b6559836 (it is the first line of the file). 

The other addresses appear to be ok, all of these interacted with our proxy and made a swap with uniswap.

**Comment by gio1983** [comment]
Address 0x04661d1e0a5c6d8436ca58de116d524a66eeeede
https://etherscan.io/tx/0x4fab40c970fe09f7cdbdddf280e08541ac360dd057e6db9a170dc4cd7c4bb242

Address 0x3e16370FC214f139903aaAf43CD2E46740c89c9c
https://etherscan.io/tx/0x74549205e4e5e97d02e659cdbc5c1df99682d5b01c2388c1e2cc23b08255c2c0

Address 0x9696d09611a52cec3d2b3019e1c7b2178115a491 is not in our list

Address 0x940cc0ae46ba774be0f11669b9e78a3f1b10b6b8
https://etherscan.io/tx/0x570aee81f4b529f6599c3296da3cb5faac0ef7faf351ce8cea338a9c30049741

Address 0xa2db46945825c50af082bc026bc4750723adfc83
https://etherscan.io/tx/0xa038bb706f84b589a3a4653f04ff5c655c1c628a585574a57ecdbb10ce004ca3

Address 0xfb0fce9d94f3f69d419dbf11cf35bed84a501034
https://etherscan.io/tx/0xbf189520235a167189694a452f8afca484ee9998e7a949fbfb3ca5d55a1b2a3d

**Comment by 0age** [comment]
Want to remove the addresses that aren't passing and then submit them in a separate PR so we can merge the bulk of them in and figure the rest out from there?

**Comment by mpolci** [comment]
I removed the addresses and rebased the branch

**Pull request merged**
